pokon548-password: ENC[AES256_GCM,data:RP2Q/v83UwiFnGliYEdobjnu62ksfdiJCcLfqfcK3Jv7MhtXjQsGtTrw3kqhDUn5IaECBYPhrLFGTyDY9kEnQR1ypR86Ybtp9w==,iv:V9UpR5FoMQbSBeX84CjstZ3asmcW1W96HcGeZ5vbG0w=,tag:oSCVK52iKvTwl+5O4PWHaQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14rfexce7p5ac2acwq5favj4c5ddna5m26jpmc0tas0nn348n0a5qazyn9x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPYm5zTlkvRnhvU3I3YThW
            Uk4rN2hhZjQrbzB3SFNxQ1FWcTViVm1Qc2pZClgycGlQK2wvR3RkM3R5KzY5Tk5i
            c3BEQ0l2NlI2dmoxbEJ0ZE1Ua3ZTdU0KLS0tIG1td2YyczJaeFZ2VWdVbThiV0Qv
            ekxZMU15d3JHWmFOeXptaGxDZlFWUHMKS6CCU16XjJg+nh9yFGEHiwZgOg6PEEEC
            Tkgj8RiNLoX2EDezPl6HzZ5W+QKmXHzArcN9paC9wXZXeaPhe/5yEw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1vcy4xzcz050ncalv78u94xphft9eq4cgx83pnxxqsks9w9tsd4wq7j46wc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzcUNwTUt4OWJNWGpKRGp0
            NWg4WXRMSG9kTEVQM2V2VkpBZmpUcXZXWEVBCjFyV0M1NWdsYWdWUkhBVGhXK3hC
            ZTBEb0EweXlWSXFCZGhIcFVUT2V1UFkKLS0tIEJmWnJwWWxDSldtNWwxcG9rTEVG
            OGg2SEJ1VVlJejRQQkpOSjgwZXNxVjQKbmn01bMpdUBfUwsbEXotmSectoM5TdJ0
            NDDJgL8JZmxidTDUPLCBsf/0wkP2ZBIr+msXKfkZ4IbOYStG6msDuw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-27T13:38:45Z"
    mac: ENC[AES256_GCM,data:xF53vNH6FzjpKTRyaeBnj3QUOy30W9xKJl2qUOfXsT1GF3BINSwqZ5iertTRqQJiomfvpHUUzeupsmj54tWFbTvOlaIHdv2DhmjP5NfKz43/5fTpBifpmpazHtDwlq37ODIy5YAQYwjV74Gx5iVIitXM8Az8e9YvaK067lcsPks=,iv:w8aVYYbFzFwM8sipJQCqb5tTvuv2le0drmQKWwhB7N8=,tag:Z8/RwUmo/VCBcny0mkBKxg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
