pokon548-password: ENC[AES256_GCM,data:5yrZ/8IA2cDoc8Rzt0Z3jJBJ1X2X8SO1BYgFfsYmR5eSlGH0eK8G/Ib6MoHk6L2Cg55XnHj0nusals8Ydo98y2bZ6h3qOKO2Ww==,iv:xtsXwXfpvOi1vp7m5c16BFo30rHjP7Ac7QrpNGliXgc=,tag:l1P0mxCTrAjGcxHpv2+dOg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1znxxn4jk8xesqmzkcz0clf7xadcq8l6dq2tsg34phvuhw8y2hquq4wmfyu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1cWptUXN1bkFXN1RCWEFk
            UUZJSHkxUVFUSTZhWEZPOUJtUi9hM0FNeFJRCnFIdWwwQ3Y2QkpZb1dUcWJ4M1Uv
            eUlvQk9WcFhSYUdhS1VMZDN5cm5SdzQKLS0tIE1XT1A2bTdJcEgxWUJHaXp1SmFx
            R1ZnOWw4NjkwcXZ2dTYxaG0xQWZ6TVUKGikQT0V2QUf3tDJGt4x9P5d5WdTPVq2X
            ztmHC4MwOmEYYwv6BTpnIJUH3iwfqxcDjbjQrn4xGkqDxZY0sfUkVA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14rfexce7p5ac2acwq5favj4c5ddna5m26jpmc0tas0nn348n0a5qazyn9x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYcGhib05XdW9SQ2ZIQ0t0
            WWJCS1N4UEVvblNRRG4xSnBQTEY1QkduR25NCnlqTEVHSkhqYjMwTDFhUmdzeFRV
            ZDlCbkkvU21yS2RabnhwRWxuZERJVGsKLS0tIFFjLy8rRHhLZzgxc1paN2YxQUls
            Qlh6M3k2TlY4TGZ1SzVIRzhGMFZXa0UK3JcwzfZhDUyb/Eiuf4348A3QxQHAc1zi
            TzL61LyZ4ThwLeiS0mEMoO3qXk7QEtcvzSnvMrQEr6lQy2UKfl4fWg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-29T12:27:38Z"
    mac: ENC[AES256_GCM,data:2V3dJf0EYfKJqHvoBNKEwu9U3uryI3mfpR3fSoiGxNsWv8oVNuwjexz0SyqevXlGqZb5LcXPbaJKexiEmHACAzQTAr5CqXx0mHQW3Rl42v3cmdos7OWc4YeBS5mmreGKM9yPtxZ/xHS+JsVq3L3vdXs96vu/NTL5rtciXRNYh+g=,iv:BVEIdrCTEEec4WoMvh9NNSfMEhKjPlH4bVzX1m8Qw/4=,tag:IJgFsxdF9apsgYwWlrAJ0w==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
