pokon548-password: ENC[AES256_GCM,data:MegYjtbf8PbKozQLc0NNZBHYd/Eb8/CIZntu0FuwDomljUa/URqF9HeurZjjNYFDrNEqELyJ1VlHwcjuC2w1B0+XRGT1dsOuWg==,iv:K+KhY4A3ybapLK55hs6FVwcK0vb+DblGCRQDXq3qySU=,tag:Baox7OoltXVzVdR/EjcDBw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1vcy4xzcz050ncalv78u94xphft9eq4cgx83pnxxqsks9w9tsd4wq7j46wc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYNjYxdUNETnRhTlJjTGpB
            UTQ2ajErcXhleXYzWUNhZWJqdklMS0dxQkF3CjA0cklsUVBITDlDbWRjTVdGOEZ3
            NENDT0FNcUNVVFlwbkM1clZoVEF4aUUKLS0tIFU3eU9Qd2NLa1ArRjRiOGFiWW5o
            L1d3U0pOVVJZeEo4WEtpSk9JOVY3ancK4qFjACMe88eGcq+dcphLcb/bBxUtuIFR
            cJkAO6KlxvvylTlUS0o5Lf/WcQLFMfJ60iRnurPpEiTW/heILQ8QoA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ddpm50l0nzfnd3wuvd0efm9h4nqvrskrdmjqqfsyhjn05erakuhq8ku76m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFbnExOTZDN0oxY05XWFda
            ZTlBeDhxMzFkN2prZlMzQWNkRzU0cHVOMlVrCjhGNGoxVFNhVVV0RHdXR05KNkY4
            NGZmWkM2ZC9YUjRvSHpKbXdkM25MdjQKLS0tIFRGZVJqcnlyemdaTjhtNERER2xO
            UitnZEthVmFBdWRUajNwYWVSdjN1Nm8KGbsXMNZCBk7vcWXZ6XsJQxOHTF+LpstP
            hQW7Yz42Fu/nNRApwHK6gsBWZaFsX/Oelhw2S0q6hq73K/Bt04VG7w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-24T15:04:00Z"
    mac: ENC[AES256_GCM,data:osmfWm3VQDvmlM2uhAX0wuemSkE2VDKTQCLdazwKXvBZ4nklp8FbYEXJocRBO+3TkMc8V6nQiIXPBLlRCaASikgZ3ae7g2e9fQH6CnZWNUbE4AvimbpU1SAobXzihId+I8kFwu3wIZ0XJCsHmWsJ54FSihrVnnrZl+x6Agkqwl8=,iv:9pdKkdZ100IXklyxt/8S7esjCdppBpcAjkMhhyR9mR0=,tag:RXVzYYCFXTI/vx8T37GdhA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
