pokon548-password: ENC[AES256_GCM,data:hT1s1fHnUa0SHM72CYvKwl3Dgs084HrtSPectYBvs2XQm1a/IP6DYjZjZeLZaKBqPH8XSsFOMNT5eTXWzNOObq1Wj00U6HeRvg==,iv:YONrfuJHKDDQXkvF1WRrgAxJyudlKQOdndh/s/Y+6lQ=,tag:LS2Cld+mAZ69DdRESw504g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1vcy4xzcz050ncalv78u94xphft9eq4cgx83pnxxqsks9w9tsd4wq7j46wc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIT1o3QWxscWt4ODJQWWlG
            MFJlZzc5OE80YUFPQ0JXYm9KT1pKMXRIN2hBCkhyZ25jeTZ6UStTRlAxQno5dldK
            S0o5WE04NG9HaGpOU2NNdjJNSzR4TUUKLS0tIE5kOFNWNGVQSEZkR0VIZFZiNUMv
            TWpNWVU5YzVJa0dVN2MydHluSG9DM0UKK5e7W9T+x7uuINBOGwm9xwl6LJEtw5nr
            DCG9uqHjdKi/9o3ABM0N5+YCcC4DE+FGhhqmb2yFXdMo0ei/mtmqDA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-04T04:44:15Z"
    mac: ENC[AES256_GCM,data:Pu9DBlZO2/4Sh7t7DUaWqSuYb1JvGqCm7SniKy+Rm883x6kRWKeeK9BVs25cVmE5b13430Z+RX30bdu8elYg/DqOnywisc7fKvIsoGZHv8UbN87L2Lq9A5NMP23O5HpoD0tVlsp+AeU9Y7Y975dx4PbC16Vh5y4sQg097iZ3AzI=,iv:Njf6SPWiPkVtLs95pHGgXFLUTGiTaIoeS47YR+VTvc8=,tag:uY9IeeaMoyWm/N6X51QeFw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
