pokon548-password: ENC[AES256_GCM,data:xl+SFqbv0O1qYER4fBfuCR2skno8w2QTnGH51wBstmMUIkOLlNAlZnqjJPUceOFjQt4iM+cKY8VcC65GNNf1cR1/o+mNVKvb+g==,iv:KFz3v7mltwlmZCLAdgnUijiBjoy5CHEgWUf9MUF5gUQ=,tag:kOlieyg4rkbgIPormOabSQ==,type:str]
tailscale:
    auth-key: ENC[AES256_GCM,data:lzMuMZh8vm+Gk7ntTRQpOsEaewPsR+KLotIipknjErAJpn3BfRTdNJXJPE1IluoB,iv:i5k2m6n8wmCK0R6rIoenH22xtWWff8nl27KIlvNrZ+o=,tag:b0qYLwsrEC+/k9FpdiJCIw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1znxxn4jk8xesqmzkcz0clf7xadcq8l6dq2tsg34phvuhw8y2hquq4wmfyu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDT01TaVV4MElWdXNzaHk1
            eTF3T1pZcUFBelJTSXBkdUU2R3ZMOXY3UEVRClJoUlNPNXR3dElaMm5mWlJ3MTRW
            RTFEbjdvWE9DaWEzY3U5UXE2NUpKbzAKLS0tIEprZGo0MVhWZVBJbHdWb05BME9m
            YnFGUjU3ZnNkdStnQm5FdzFzRm5OUVkKORjQSOuciulfNLm2htmKhVHWAEfdgbcY
            HtEZ30EWncuh6L/LrPUN00lHcEIZLHqrbOVF5CxJTZ3NqEaMF2pC+Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ddpm50l0nzfnd3wuvd0efm9h4nqvrskrdmjqqfsyhjn05erakuhq8ku76m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6SGo3OUJvaVBRWFpUZ0JH
            M1c5UEtnc2dsVUxSR2wrRDhFZE9URFdXZ0dVCkkxVDFVc0xIK3dyN0RvMXV6bUh1
            S2ZDdFVValFQSjhZL25KZGVFSmxkSDQKLS0tIGdITm1pQTd6SnlxZ2V4WmNTUmdS
            aTJJVlprT0RaQ1NVRVlvVlhUQWlXdWsKtfTkCp6WSl0GPykjRjERhCkU/Nu8zWm8
            aZU8VfvC4xBIQeW6B5tn+psMYyvlJzFvpkYdHEGfbbtTLS0nSaHbsA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-02T09:48:18Z"
    mac: ENC[AES256_GCM,data:iTPq8wQYRCyDvRicno/kSDeIgA/dhU0d0RFep3i7kSLfKEZnLtXOH3XD0yI1Hm/ESpU/auZh6aaogRmPqe8K25GwcFjgqk18UhwTCVxMmLT4iTp50yvUKcwYRm3jSWfzoOBWQCVxlEajJgqo6tbx/DzpRmea+9goiWHWwuWT8nA=,iv:TVd3U53GJMwm5V1AjlJ+mbn3OP6+xW0MvMP7RywjvaM=,tag:8GUNAeW8ByScRJ0IJWXYCw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
