pokon548-password: ENC[AES256_GCM,data:xl+SFqbv0O1qYER4fBfuCR2skno8w2QTnGH51wBstmMUIkOLlNAlZnqjJPUceOFjQt4iM+cKY8VcC65GNNf1cR1/o+mNVKvb+g==,iv:KFz3v7mltwlmZCLAdgnUijiBjoy5CHEgWUf9MUF5gUQ=,tag:kOlieyg4rkbgIPormOabSQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1znxxn4jk8xesqmzkcz0clf7xadcq8l6dq2tsg34phvuhw8y2hquq4wmfyu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDT01TaVV4MElWdXNzaHk1
            eTF3T1pZcUFBelJTSXBkdUU2R3ZMOXY3UEVRClJoUlNPNXR3dElaMm5mWlJ3MTRW
            RTFEbjdvWE9DaWEzY3U5UXE2NUpKbzAKLS0tIEprZGo0MVhWZVBJbHdWb05BME9m
            YnFGUjU3ZnNkdStnQm5FdzFzRm5OUVkKORjQSOuciulfNLm2htmKhVHWAEfdgbcY
            HtEZ30EWncuh6L/LrPUN00lHcEIZLHqrbOVF5CxJTZ3NqEaMF2pC+Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ddpm50l0nzfnd3wuvd0efm9h4nqvrskrdmjqqfsyhjn05erakuhq8ku76m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6SGo3OUJvaVBRWFpUZ0JH
            M1c5UEtnc2dsVUxSR2wrRDhFZE9URFdXZ0dVCkkxVDFVc0xIK3dyN0RvMXV6bUh1
            S2ZDdFVValFQSjhZL25KZGVFSmxkSDQKLS0tIGdITm1pQTd6SnlxZ2V4WmNTUmdS
            aTJJVlprT0RaQ1NVRVlvVlhUQWlXdWsKtfTkCp6WSl0GPykjRjERhCkU/Nu8zWm8
            aZU8VfvC4xBIQeW6B5tn+psMYyvlJzFvpkYdHEGfbbtTLS0nSaHbsA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-29T12:28:14Z"
    mac: ENC[AES256_GCM,data:l6fWMv4j835vwbq0BqB7oYVAuX49Oxjv8XP3fUyKGs9K7wPcsqFP8L7OwBKUR8l6FQYSrI4TVQ7g1wsIcLHlag14GJ7BtuRGDbz8HAA87mab/QvRN+u2qmSHTzQUIdY2hEzV8i5REX5VM2i+wCTK5tnTGBD1StDh12tYoTc5K2c=,iv:aMlxLkRwU5zqQYHa5LocxlMjxIMUt2pKXVpbenkf3hM=,tag:gfBd7PqyZW7QutrFiJ7JCg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
