kon548-password: ENC[AES256_GCM,data:Oow/XhDnCGAgnDU2Ny9rA2bc0iWTF5VB7kZfD0hYvKDbRoAhzu4oICYRrdQnV9aurqGEg8AILVr9eBJwDrs6WLOAhx4p5AxctA==,iv:yVnxoi6l1BCam+cufpI0iLomq1ySmH/UDvU2AIN6Yz4=,tag:9W26C1bQ0AnoHgPaD1kQQg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1znxxn4jk8xesqmzkcz0clf7xadcq8l6dq2tsg34phvuhw8y2hquq4wmfyu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNcFdqN3haRjJTM0QwQXp4
            WUhEMnZQWi9KRUNhNi9BeGhKMzN6NnlSU3lnCk13MFpCemFEdUg5L1BmSzdxV2hG
            Q01INy9QU092aFdVbnp4R3cydnNkWDgKLS0tIGRML2NqT2xJbGpmeWtTUlhWeEFY
            T2t6dC9uZEkzQ3RaT21DeW9xQ3QxVVkK1eARbowBnfq5zE65mKzRnuXw+aWRbTnj
            74RTbp5bTmKeyayv4X0vHgT0lAZoQkG155FVuiud8oE6yn1swpCA8w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-29T12:27:19Z"
    mac: ENC[AES256_GCM,data:SsMZHtU5s15xe7RDrdblKGUxq2pSvu4U4Zk9nAo5M8pUvwXC5O9Pdc531S8sMscRsoEpZpF5f6t74AhVo1NotWCATLJ0SIr8bYSb+Oy/RBUo8VNZ3oxnJzH8eh024El+eG2svEX6XdKsoVZ8HyB+FFcqsIDG8bxxyWbZP2NNSYw=,iv:ktbd493qDWfRoCUPhaxPstgtD/YVoD6BFf0SJv/VSPQ=,tag:BDT74+yNrAiCqvW5ixwVSA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
